version: "3.9"

services:
  db:
    image: mysql
    container_name: db_cnn
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=cgvbot
    ports:
      - 3307:3306
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  adminer:
    image: adminer
    container_name: adminer_cnn
    restart: always
    ports:
      - 8080:8080

  bot:
    build: .
    container_name: bot_cgv
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    command: python app.py

volumes:
  db_data:
